# Generated by Django 3.0.6 on 2020-05-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='useraddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='usercity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='useremail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='userdesc',
            new_name='rdesc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='userstate',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='userzip',
            new_name='zipcode',
        ),
    ]
