# Generated by Django 3.0.6 on 2020-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliohome', '0003_auto_20200530_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
